# Generated by Django 4.2.30 on 2026-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_jiraimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraimportjob',
            name='with_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
