# Generated by Django 5.2.15 on 2026-08-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        ('db', '0125_issuecomment_external_actor_display'),
    ]

    operations = [
    ]
