# Generated by Django 4.2.30 on 2026-07-15 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Hand-pinned to the newest UPSTREAM db migration that already defines
        # Workspace/Project/Issue/IssueType (design §7). Do NOT let this drift to
        # a fork-local db migration (0122+); pinning to 0121 keeps this app's
        # migration graph independent of the fork's time-tracking migrations so
        # they can be squashed/renamed during an upstream merge without breaking us.
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('TEXT', 'Text'), ('DATETIME', 'Datetime'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('OPTION', 'Option'), ('RELATION', 'Relation'), ('URL', 'Url'), ('EMAIL', 'Email'), ('FILE', 'File'), ('FORMULA', 'Formula')], max_length=255)),
                ('relation_type', models.CharField(blank=True, choices=[('ISSUE', 'Issue'), ('USER', 'User')], max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_multi', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(default=dict)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='db.issuetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property',
                'verbose_name_plural': 'Issue Properties',
                'db_table': 'issue_properties',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='properties.issuepropertyoption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_options', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='properties.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_options', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Option',
                'verbose_name_plural': 'Issue Property Options',
                'db_table': 'issue_property_options',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPropertiesFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties_feature', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_features', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Properties Feature',
                'verbose_name_plural': 'Project Properties Features',
                'db_table': 'fork_project_properties_feature',
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('value_decimal', models.FloatField(default=0)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_uuid', models.UUIDField(blank=True, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_values', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='properties.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='properties.issuepropertyoption')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_values', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Value',
                'verbose_name_plural': 'Issue Property Values',
                'db_table': 'issue_property_values',
                'indexes': [models.Index(fields=['issue'], name='issue_prope_issue_i_93c20c_idx'), models.Index(fields=['property'], name='issue_prope_propert_e8a7c3_idx'), models.Index(fields=['project', 'property'], name='issue_prope_project_00ded1_idx')],
            },
        ),
    ]
