# Generated by Django 4.2.30 on 2026-07-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Hand-pinned to the same UPSTREAM db migration that
        # plane.properties.migrations.0001_initial pins to (design doc §7);
        # it already defines Workspace/IssueView. Do NOT let this drift to a
        # fork-local db migration (0122+); pinning to 0121 keeps this app's
        # migration graph independent of the fork's time-tracking migrations
        # so they can be squashed/renamed during an upstream merge without
        # breaking us.
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('widget_type', models.CharField(choices=[('distribution_pie', 'Distribution Pie'), ('project_breakdown_pie', 'Project Breakdown Pie'), ('age_trend', 'Age Trend'), ('view_list', 'View List')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fork_dashboard_widgets', to='db.issueview')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fork_dashboard_widgets', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Dashboard Widget',
                'verbose_name_plural': 'Workspace Dashboard Widgets',
                'db_table': 'fork_workspace_dashboard_widgets',
                'ordering': ('sort_order',),
            },
        ),
    ]
